### ISSUE TITLE
how to make inference on new data ?

### ISSUE THREAD

**Issue by thegodone** [dptech-corp/NAG2G#2]
Can you share the pipeline for inference of new data ?

- data preparation ?
- valid.sh option to change ?

**Comment by thegodone** [comment]
I see the infer.py code but there are no instruction how to use it ?

**Comment by synsis** [comment]
Hello,

Here are the instructions for setting up your project folder:

1. Create a Folder and Add Files:
   - Create a new folder.
   - Place the `dict_20230310.txt` file inside this folder. You can download the file from the following link: [USPTO50K_brief_20230227.zip](https://drive.google.com/drive/folders/1lZOLRGyZy18EVow7gyxtKWvs_yuwlIE3?usp=sharing).

2. Create `test.lmdb` File:
   - Inside the same folder, create a `test.lmdb` file. Ensure that the format of this file matches the data I provided.

3. Update `valid.sh` Script:
   - In the `valid.sh` script, update the paths to match the current folder paths.

Regarding the preparation of a `test.lmdb` file from a CSV, I will upload a data preprocessing file with instructions within a week.

Thank you.

Folder Structure:
```
project_folder/
├── dict_20230310.txt
├── test.lmdb
```

Let me know if you need further assistance!

**Comment by thegodone** [comment]
Thank you, I need to test is as fast as possible, is it possible to go quicker to get csv to lmdb ?

**Comment by thegodone** [comment]
this is great! Will tell if I have any issues
